version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aa-calculator
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=./data/calculator.sqlite
      - NEXT_PUBLIC_APP_NAME=aa
    volumes:
      - sqlite-data:/app/data
    restart: unless-stopped

volumes:
  sqlite-data:
